### ISSUE TITLE
Sleep does not work actually.  (i5 Horizon)

### ISSUE THREAD

**Issue by d-kanti** [itsdrnoob/Mi-NoteBook-14-Hackintosh#3]
sleep does not seem to actually work, the fans kept spinning and device kept heating.

**Comment by itsdrnoob** [comment]
which variant, i3 or i5?

**Comment by d-kanti** [comment]
forgot to mention, i5 horizon, (i5, mx350) 
sorry

**Comment by itsdrnoob** [comment]
close the lid and wait for 15-20 seconds, and then check whether the fan is still spinning or not

**Comment by d-kanti** [comment]
i checked in every scenario i could imagine. 
-  closed the lid and waited 5 mins
- manually put into sleep using menu, and left the lid open

> in that case the screen got black and after 10-15 second it again lighted up in the login screen.

- manually put to sleep and closed the lid 
- put to sleep using power button  and left lid open 
- put to sleep using power button and closed the lid
all of the above, once while charging, once while on battery.
nothing seemed to work.

- p

**Comment by d-kanti** [comment]
anyway, the work you have done... it's wonderful. 
# Thank  you.

**Comment by itsdrnoob** [comment]
Thank you :-) BTW can you run pmset -g in terminal and attach a screenshot.

**Comment by d-kanti** [comment]
Sure 
![Screen Shot 2021-03-14 at 12 48 18 PM](https://user-images.githubusercontent.com/64345702/111060636-6487a600-84c4-11eb-9a7b-f286b0cdcb60.png)

**Comment by d-kanti** [comment]
also the wifi was finding some trouble after i tried to put it to sleep. I put it to sleep, it wakes up automatically, and then wifi does not connect anymore. I had to restart.

**Comment by d-kanti** [comment]
### This might help 
--- 

https://user-images.githubusercontent.com/64345702/111061585-255c5380-84ca-11eb-97a3-755f9e28e0c1.mp4

## I did not touch, it came back alive by it self.

**Comment by d-kanti** [comment]
one more thing maybe I should mention, if we close the lid, then the fan stops spinning after a few seconds, and stays stop for 2-3 sec, then starts again, then again stops after a few seconds for 2-3 sec, and so n, keeps repeating the same pattern.

**Comment by chadify** [comment]
> ### This might help
>  2021-03-14.13.31.04.1.1.mp4 
> ## I did not touch, it came back alive by it self.

I'm having the exact same issues with my i7 Horizon edition. Sleep is broken. Do notify me if you find a fix.

**Comment by itsdrnoob** [comment]
sudo pmset autopoweroff 0
sudo pmset powernap 0
sudo pmset standby 0
sudo pmset proximitywake 0
sudo pmset tcpkeepalive 0

try these commands in terminal.

For the wifi, it is a problem with the internal wifi, use heliport instead

**Comment by d-kanti** [comment]
> sudo pmset autopoweroff 0
> sudo pmset powernap 0
> sudo pmset standby 0
> sudo pmset proximitywake 0
> sudo pmset tcpkeepalive 0
> 
> try these commands in terminal.
> 
> For the wifi, it is a problem with the internal wifi, use heliport instead

i saw them in the open core doccumentation, i tried them, does not work.

**Comment by d-kanti** [comment]
can you please guid how to use heli port ? instead of internal wifi ? just putting it into the login application ? 
or some other steps need to be taken ?

**Comment by itsdrnoob** [comment]
you need to enable/disable kexts in config.plist too. Add itlwn.kext to OC/Kexts and also add it under Kernel in config.plist and make sure it's enabled. Also disable airportitlwm.kext from config.plist

**Comment by d-kanti** [comment]
enabled itlwm, disabled airportitlwm.  did not work. issue still exist

**Comment by itsdrnoob** [comment]
what exactly is the issue you're facing

**Comment by d-kanti** [comment]
> what exactly is the issue you're facing

speaking in short, it is going in a sleep-wake cycle type of something. waking automatically, not actually sleeping. 
https://github.com/itsdrnoob/Mi-NoteBook-14-Hackintosh/issues/3#issuecomment-798857757  is a reference of what is happening.

**Comment by itsdrnoob** [comment]
Ok. but i was actually asking about the heliport issue ..

**Comment by d-kanti** [comment]
> Ok. but i was actually asking about the heliport issue ..

the heli port is working fine after modifying config.plist. even works better than the airportutility, but the issue with the sleep was still exixting. 
- it was still waking up on its own. that's the problem.

**Comment by itsdrnoob** [comment]
can you try out some old versions of the efi and check whether the issue is still there

**Comment by d-kanti** [comment]
> can you try out some old versions of the efi and check whether the issue is still there

I did. still exist. i tried the First EFI (20th Dec) and a few more, but it still exitsts.

**Comment by d-kanti** [comment]
i had another doubt, can you please tell me which file system did you use while formatting the ssd for mac ? did you use apfs ?

**Comment by d-kanti** [comment]
i had another doubt, can you please tell me which file system did you use while formatting the ssd for mac ? did you use apfs ?

**Comment by itsdrnoob** [comment]
i'm not sure, ig i used macos extended. I forgot 😅

**Comment by PhantomZNeuroX** [comment]
@d-kanti  Hello, I see that you had succes with installing macOS big sur on MI Notebook 14, Could you help me with it I am facing a few issues, Could you write down the steps that you took to install macos? Thank you :)

**Comment by d-kanti** [comment]
@PhantomZNeuroX   it would be really appreciated if you also mention the issues you are facing, so that exact problem to be pin pointed. 

And also remember to use 'APFS' file system while formatting the drive. Macos extended dkes not work.

**Comment by PhantomZNeuroX** [comment]
> i

Sure, Here are the steps i followed :-
1)Using GibMacOS i downloaded big sur
2)made a apple recovery folder
3) downloaded and copied the EFI folder to the pendrive, using SMBIOS I changed the UUID and stuff in config.pilist
4)Booted via usb, wiped my drive and then started the installation
5) Here i faced numeroes internet issues but after that the installation was stuck at 13 mins

and there were a few other issues here and their but this was the main issue, due  to this i tried for Big Sur offline installer but, couldnt complete it so i decided to install catalina offline with this EFI after booting through it , the installer said that this image of catalina might be damaged and didnt let me do anythin :(

**Comment by d-kanti** [comment]
@PhantomZNeuroX 

Thank you for sharing. Some points i would like to mention.

1) The efi folder might not work with Catalina. I tried to install Catalina (as i had the sleep issue with bigsur) but it did not work. 

2)  you may try to without changing the uuid. Just copy paste the efi. After installation, change the uuid to the desired uuid and copy it to the mac's efi partition. Changing uuid after installation works without any issue. 

3) I once faced an issue of the mac being download and then again being redirected to the starting page. This issue occurred when i was formatting the drive using Mac OS extended format. The issue was solved when I used APFS file system to format the drive. Keep this in mind.


I used recovery. I never needed to make a offline installer, so i didn't try. Can't comment anything about that. 

I would suggest steps
1- copy recovery image and efi to usb
2- boot from usb
3- format whole drive to 'APFS' file system. (remember, whole drive. Not a partition. Use command+2{alt+2} to view all) 
4- install macos on the drive. ( Time needed for download and installation seperately.)
5- wallah, my devices booted up here. 
6- then i changed my uuid. But made sure i had a copy of the efi so that i could always boot with that efi, (waiting hours is a pain) 

You may try these... Please let us know if the issue gets resolved.

**Comment by PhantomZNeuroX** [comment]
> @PhantomZNeuroX 
> 
> Thank you for sharing. Some points i would like to mention.
> 
> 1) The efi folder might not work with Catalina. I tried to install Catalina (as i had the sleep issue with bigsur) but it did not work. 
> 
> 2)  you may try to without changing the uuid. Just copy paste the efi. After installation, change the uuid to the desired uuid and copy it to the mac's efi partition. Changing uuid after installation works without any issue. 
> 
> 3) I once faced an issue of the mac being download and then again being redirected to the starting page. This issue occurred when i was formatting the drive using Mac OS extended format. The issue was solved when I used APFS file system to format the drive. Keep this in mind.
> 
> 
> I used recovery. I never needed to make a offline installer, so i didn't try. Can't comment anything about that. 
> 
> I would suggest steps
> 1- copy recovery image and efi to usb
> 2- boot from usb
> 3- format whole drive to 'APFS' file system. (remember, whole drive. Not a partition. Use command+2{alt+2} to view all) 
> 4- install macos on the drive. ( Time needed for download and installation seperately.)
> 5- wallah, my devices booted up here. 
> 6- then i changed my uuid. But made sure i had a copy of the efi so that i could always boot with that efi, (waiting hours is a pain) 
> 
> You may try these... Please let us know if the issue gets resolved. 

Okayy thanks :) , one question where did you install the big sur recovery frm?, I can't see big sur recovery on gib MacOS


anyways I'll try this 


if you still have your pendrive could you send me all the files I  your pendrive?, I'll try it with that, I think the issue was due to me using the wrong recovery possibly?

**Comment by d-kanti** [comment]
Possible. 

https://youtu.be/eUnVzJsINCI

I followed this video to create recovery. I will send files later, meanwhile, try method shown in video. (Jump to 11:40 )

**Comment by PhantomZNeuroX** [comment]
oh okay, have seen this aldredy, but still cant find big sur recovery files

Thanks :)

**Comment by d-kanti** [comment]
I will send the files.

**Comment by d-kanti** [comment]
@PhantomZNeuroX 

https://1drv.ms/u/s!Am-re1MeIEGyhaA6AvqCW-Ji5X_Nrw

You may download and extract the zip file...

(Link valid for 3 days only)

**Comment by PhantomZNeuroX** [comment]
Thanks will tell you my result

**Comment by PhantomZNeuroX** [comment]
> @PhantomZNeuroX 
> 
> https://1drv.ms/u/s!Am-re1MeIEGyhaA6AvqCW-Ji5X_Nrw
> 
> You may download and extract the zip file...
> 
> (Link valid for 3 days only)

it's stuck at 13 minuites again :(
 
I don't understand what is the PROBLEM 😔

Any solutions? i haven't closed it yet

**Comment by PhantomZNeuroX** [comment]
> @PhantomZNeuroX 
> 
> https://1drv.ms/u/s!Am-re1MeIEGyhaA6AvqCW-Ji5X_Nrw
> 
> You may download and extract the zip file...
> 
> (Link valid for 3 days only)

![IMG_20210417_155124.jpg](https://user-images.githubusercontent.com/53567039/115109681-e15ee180-9f94-11eb-91c3-272a7162fead.jpg)

![IMG_20210417_155134.jpg](https://user-images.githubusercontent.com/53567039/115109687-ea4fb300-9f94-11eb-8b6d-0c9fa57e873d.jpg)


:(

**Comment by d-kanti** [comment]
No idea.... Can you try over some.other network? Might be a network issue... ?

**Comment by PhantomZNeuroX** [comment]
hhmmmmmm that's what I had assumed as well, so I tried with my hotspot which was painstakingly slow, I don't remember particularly well but i think I had gotten the same error. I might try to do this at a friend's house cu it dosent seam to work with my hotspot, any router settings u think I should change?

**Comment by d-kanti** [comment]
Not sure about any settings change.... Changing the dns might work, but nit sure if it will work, or what would be proper dns... No idea about that. 

I recommend trying with some friends house, or cyber cafe or something like that.. mobile hotspot should be slow... And download 13gb over it....   Its just unbearable.

**Comment by itsdrnoob** [comment]
NOTE: 
Installing Catalina and updating to Big Sur seems to fix many issues. iServices are also working.

**Comment by d-kanti** [comment]
i was unable to install catalina using your ufi as far i remember. there was some error showing up which i don't remember. 

I will try once again, 

btw, did you find anything about the sleep issue ? @itsdrnoob  
a properly working sleep feature would be great.

**Comment by itsdrnoob** [comment]
Update the kexts (excluding WhateverGreen & VoodooPS2Controller) and set this as the bootargs : 
`darkwake=0 gfxrst=1  agdpmod=pikera alcid=21 -disablegfxfirmware -hbfx-disable-patch-pci -hbfx-dump-nvram hbfx-ahbm=3`

**Comment by d-kanti** [comment]
Can you please instruct me how to update the kexts ?

**Comment by itsdrnoob** [comment]
- Install hackintool and navigate to Extensions tab.
- Select the kext and click download button (the center one).
- Replace the kexts in OC/Kexts.
- Reboot.

![Screenshot 2021-04-25 at 9 12 35 AM](https://user-images.githubusercontent.com/52557407/115980008-f0521f00-a5a6-11eb-8459-b5f3ee6ac2fe.png)

Or you can manually download the kexts from their github repo and replace.

**Comment by d-kanti** [comment]
Thanks @itsdrnoob  

Also can you say what filesystem you used while formatting the drive ? Apfs or macos extended ?

**Comment by itsdrnoob** [comment]
APFS

**Comment by d-kanti** [comment]
And exact version of Catalina ?

**Comment by itsdrnoob** [comment]
10.15.7

**Comment by sandeepkandula09876** [comment]
Hey bro can u make full installation video

**Comment by nabilpatel4012** [comment]
Hey Brother I wanted to ask just one thing that is from where do I have to download and how do I burn the ISO image

**Comment by itsdrnoob** [comment]
> Hey Brother I wanted to ask just one thing that is from where do I have to download and how do I burn the ISO image

If you have access to a mac, download the official installer from app store.
I used a raw image from olarila.com, burn it using balena Etcher

**Comment by nabilpatel4012** [comment]
> > Hey Brother I wanted to ask just one thing that is from where do I have to download and how do I burn the ISO image
> 
> If you have access to a mac, download the official installer from app store.
> I used a raw image from olarila.com, burn it using balena Etcher

And one more thing bhai what you did at the time of recovery, that means I tried to do it by the dortania guide but just replaced that efi with yours and it worked perfectly but at the time of recovery my internet was not working not the wifi and not the external dongle so how can I fix that or it will be fixed when I use olarila image???

**Comment by nabilpatel4012** [comment]
Can I do same thing with catalina instead that is just replacing the EFI??
Please answer these I will be very thankful to  you  👍

**Comment by itsdrnoob** [comment]
> > > Hey Brother I wanted to ask just one thing that is from where do I have to download and how do I burn the ISO image
> > 
> > 
> > If you have access to a mac, download the official installer from app store.
> > I used a raw image from olarila.com, burn it using balena Etcher
> 
> And one more thing bhai what you did at the time of recovery, that means I tried to do it by the dortania guide but just replaced that efi with yours and it worked perfectly but at the time of recovery my internet was not working not the wifi and not the external dongle so how can I fix that or it will be fixed when I use olarila image???

Yes, you don't require an internet connection when using olarila image

**Comment by itsdrnoob** [comment]
> > > Can I do same thing with catalina instead that is just replacing the EFI??
> > > Please answer these I will be very thankful to you 👍
> > 
> > 
> > The i3 variant booted catalina successfully, you can try booting catalina.
> 
> Yeah thank you son much Bhai But I have the Horizon edition so will it work or not??

No idea, it should ig, the only way to find out is to try it.

**Comment by d-kanti** [comment]
> > > Can I do same thing with catalina instead that is just replacing the EFI??
> > > Please answer these I will be very thankful to you 👍
> > 
> > The i3 variant booted catalina successfully, you can try booting catalina.
> 
> Yeah thank you son much Bhai But I have the Horizon edition so will it work or not?? 

@nabilpatel4012  please let us know if it works.

**Comment by nabilpatel4012** [comment]
How can I change the efi folder after burning the olarila image??

**Comment by nabilpatel4012** [comment]
@d-kanti  yup I will share you further details but first thing first I want to know is how can I replace the efi folder with this one??
There are no efi folders at all in the burned image of macOS

**Comment by itsdrnoob** [comment]
> How can I change the efi folder after burning the olarila image??

Assign a letter to the partition using minitool partition wizard, then use explorer ++ to replace the efi.

**Comment by nabilpatel4012** [comment]
Yeah I done that also now I have one confusion that is the contents in the folder EFI of the pendrive are OC BOOT and CLOVER, So it is fine or I have to do something else or I have 

> > How can I change the efi folder after burning the olarila image??
> 
> Assign a letter to the partition using minitool partition wizard, then use explorer ++ to replace the efi.

Yeah I done this but now I have a little confusion, that is my pendrive's EFI folder is showing content like OC BOOT and CLOVER, so this is correct or I have done anything wrong?

**Comment by itsdrnoob** [comment]
> Yeah I done that also now I have one confusion that is the contents in the folder EFI of the pendrive are OC BOOT and CLOVER, So it is fine or I have to do something else or I have
> 
> > > How can I change the efi folder after burning the olarila image??
> > 
> > 
> > Assign a letter to the partition using minitool partition wizard, then use explorer ++ to replace the efi.
> 
> Yeah I done this but now I have a little confusion, that is my pendrive's EFI folder is showing content like OC BOOT and CLOVER, so this is correct or I have done anything wrong?

Replace both with the Efi's Boot and OC

**Comment by nabilpatel4012** [comment]
> > Yeah I done that also now I have one confusion that is the contents in the folder EFI of the pendrive are OC BOOT and CLOVER, So it is fine or I have to do something else or I have
> > > > How can I change the efi folder after burning the olarila image??
> > > 
> > > 
> > > Assign a letter to the partition using minitool partition wizard, then use explorer ++ to replace the efi.
> > 
> > 
> > Yeah I done this but now I have a little confusion, that is my pendrive's EFI folder is showing content like OC BOOT and CLOVER, so this is correct or I have done anything wrong?
> 
> Replace both with the Efi's Boot and OC

That is correct bhai I have replaced those folders but there's another one CLove folder what to do about that??

**Comment by itsdrnoob** [comment]
> That is correct bhai I have replaced those folders but there's another one CLove folder what to do about that??

Please attach a screenshot

**Comment by nabilpatel4012** [comment]
![Screenshot (316)](https://user-images.githubusercontent.com/80565100/117562755-fd026700-b0be-11eb-8161-8d813b48d1dd.png)

**Comment by PhantomZNeuroX** [comment]
Hello ... it's me again😂

okay so after some long ideating I was able to install big sur after switching my router for a raspberry Pi and adding a vpn to it I was able to get it working and it installed fine but here comes the complex part, the wifi is a bit broken , I can see all the connections but I sometimes I am not able to connect, when I do connect I keep getting disconnected and all all, also only 1 out of my 3 usb ports are working in macos haven't tried the thunderbolt yet


Am I doing something wrong and if so is this a easy problem to fix?

**Comment by PhantomZNeuroX** [comment]
> Hello @PhantomZNeuroX 
>    It's good to hear from you after a long time. I'm glad it worked for you Afterall, though am sorry hearing about the inconveniences you are  facing. 
>  
> 1) i agree wifi is a little bit broken, but it do not make you disconnected. Sometimes it takes time to connect, but the disconnection part.... It again might be an issue of router or something.... @itsdrnoob might have fix, i have no ideaa. 
> 
> 2) i have no idea also for why your usb ports are not working. It worked absolutely fine for me. And i think for everyone else. Thunderbolt should not work though, due to lack of hardware. 
> 
> 3) can you please let me know if your device sleeps... Or wakes up automatically.... Like 
> 
> https://user-images.githubusercontent.com/64345702/111061585-255c5380-84ca-11eb-97a3-755f9e28e0c1.mp4
> 
> Please let me know

Nope, the sleep isn't working for me either . for now I am going to try and re download the EFI as I think I might be using a older version

**Comment by d-kanti** [comment]
@PhantomZNeuroX  thanks for the information. The older versions of efi also didn't work for me... I tried. Let me know if any work for you..

**Comment by PhantomZNeuroX** [comment]
Yup I did some work and was able to get the wifi working as well, I am actively looking for a fix for the internal mic and sleep , If I figure out something will sure be to reply

Also, I am not able to use face timenot imessages

I have aldredy changed my serial number and everything but still

in face time it just brings me back to the login screen same with Imessages

**Comment by itsdrnoob** [comment]
@PhantomZNeuroX What's your exact big sur version? Also if you face any further wifi issues, try using heliport instead.

**Comment by PhantomZNeuroX** [comment]
> @PhantomZNeuroX What's your exact big sur version? Also if you face any further wifi issues, try using heliport instead.

I am on big sur version 11.3.1

Yup aldredy tried Heliport it didn't work idk why exactly I have aldredy placed the item kext

**Comment by itsdrnoob** [comment]
> I am on big sur version 11.3.1
> 
> Yup aldredy tried Heliport it didn't work idk why exactly I have aldredy placed the item kext

Usb issue started in version 11.3.1, usb works fine in previous versions, still don't know the exact reason. And for heliport, try using a different version of the kext + disabling AirportItlwm.kext

**Comment by itsdrnoob** [comment]
@PhantomZNeuroX Well the fix was actually simple.
Just open config.plist in OpenCore Configurator, navigate to kernels tab and disable XhciPortLimit.
![Screenshot 2021-05-12 at 3 20 47 PM](https://user-images.githubusercontent.com/52557407/117955462-b1a5be00-b335-11eb-986e-eced994a0e1c.png)

**Comment by d-kanti** [comment]
> > @PhantomZNeuroX What's your exact big sur version? Also if you face any further wifi issues, try using heliport instead.
> 
> I am on big sur version 11.3.1
> 
> Yup aldredy tried Heliport it didn't work idk why exactly I have aldredy placed the item kext

@PhantomZNeuroX you also have to enable "heliport"  and disable the "airportltlwm.kext"  by modifying the 'config.plist' file.

**Comment by d-kanti** [comment]
> @PhantomZNeuroX Well the fix was actually simple.
> Just open config.plist in OpenCore Configurator, navigate to kernels tab and disable XhciPortLimit under Quirks
> 

Fix for usb ports ??

**Comment by itsdrnoob** [comment]
> Fix for usb ports ??

Yes, a quick fix for usb

**Comment by PhantomZNeuroX** [comment]
> @PhantomZNeuroX Well the fix was actually simple.
> Just open config.plist in OpenCore Configurator, navigate to kernels tab and disable XhciPortLimit under Quirks
> 

Thank you so much :) it worked

**Comment by PhantomZNeuroX** [comment]
> > > @PhantomZNeuroX What's your exact big sur version? Also if you face any further wifi issues, try using heliport instead.
> > 
> > I am on big sur version 11.3.1
> > 
> > Yup aldredy tried Heliport it didn't work idk why exactly I have aldredy placed the item kext
> 
> @PhantomZNeuroX you also have to enable "heliport"  and disable the "airportltlwm.kext"  by modifying the 'config.plist' file.

no need anymore, I did some research and found that I'd I were to use heliport air drop won't work I don't really need it but it won't and my wifi does seem to work right now so won't change anything for now

**Comment by PhantomZNeuroX** [comment]
Also one thing I would like to report is that I kept my laptop on and wasn't around for 10 to 15 mins or so when I returned the screen was black and anything I did I couldn't wake it up or do anything so I forced shut down my laptop and than. I turned it back on and on the screen where I choose to boot into MacOS or windows , I wasn't able to use my arrow keys, by default it tries to boot into windows. so I basically couldn't open either windows or MacOS. at first I suspected a hardware issue but then thankfully I was able to open the bios password screen which made me think it wasn't a hardware issue. after this I still couldn't do anything as I wasn't able to type the bios password.at the end I  had to use my phone as a keyboard to do it as the only USB keyboard I owned wasn't working properly

at the end I was able to login back into MacOS and it fixed Evrething.

I suspect that this issue has something to do with how the kext work and that we should force shutdown the laptop while in macos

**Comment by itsdrnoob** [comment]
> Also one thing I would like to report is that I kept my laptop on and wasn't around for 10 to 15 mins or so when I returned the screen was black and anything I did I couldn't wake it up or do anything so I forced shut down my laptop and than. I turned it back on and on the screen where I choose to boot into MacOS or windows , I wasn't able to use my arrow keys, by default it tries to boot into windows. so I basically couldn't open either windows or MacOS. at first I suspected a hardware issue but then thankfully I was able to open the bios password screen which made me think it wasn't a hardware issue. after this I still couldn't do anything as I wasn't able to type the bios password.at the end I had to use my phone as a keyboard to do it as the only USB keyboard I owned wasn't working properly
> 
> at the end I was able to login back into MacOS and it fixed Evrething.
> 
> I suspect that this issue has something to do with how the kext work and that we should force shutdown the laptop while in macos

Yes that happens once in a while, still needs to figure out the exact issue, keeping macos as your default os might be little helpful.

**Comment by PhantomZNeuroX** [comment]
> Just open config.plist in OpenCore Configurator, navigate to kernels tab and disable XhciPortLimit under Quirks
Hey anyone turning of XhciPortLimit using OpenCore Configurator, take a back up of your EFI folder or it might not end well,
I did this a week or two ago and then after a few days it didn't boot, might be something else I did not sure but take a backup before doing anything well.

Also wanted to ask is there a way for me to make macOS the default option during startup?

another thing, anyone who installed windows as well, it happens that windows generally docent boot from the OS select menu so what you can do is in bios settings change the boot device order whenever you need to boot into windows

**Comment by d-kanti** [comment]
I keep two efi partitions on my ssd, one contains this efi for the mac, the other one was windows's  default boot loader.  As mac is aussom but I can't leave windows either due to work reasons.... I need both time to time. It helps.

**Comment by itsdrnoob** [comment]
@PhantomZNeuroX To set macos as the default, System Prefs >> Startup disk.
Also, did you install macos by creating a partition from windows?

**Comment by PhantomZNeuroX** [comment]
> @PhantomZNeuroX To set macos as the default, System Prefs >> Startup disk.
> Also, did you install macos by creating a partition from windows?

Nope, as far as I know it's not exactly possible right , I sure would have been convenient but not possible right?

I installed windows later, I always keep a windows pendrive so I booted via it and ran some commands and it worked, I can link the tutorial I followed if anyone wants

Thanks!

**Comment by PhantomZNeuroX** [comment]
> @PhantomZNeuroX To set macos as the default, System Prefs >> Startup disk.
> Also, did you install macos by creating a partition from windows?

in startup disk the only option I have is MacOS, cant see windows there

**Comment by d-kanti** [comment]
@PhantomZNeuroX  i didn't understand actually, if you installed windows later, then it should wipe the efi partition and install windows boot manager in there. And as a result you should not see any option to boot into mac. I am a little Confused

**Comment by PhantomZNeuroX** [comment]
https://youtu.be/ztxHRGdX0Sw

@d-kanti  This is the guide I followed, after following it all I did was I created a new partition and copied the EFI folder to the new partition

**Comment by PhantomZNeuroX** [comment]
Hello, after talking to some more people, I have found a few things to get the sleep or mic to work

for the mic:- someone suggested to use a custom layout for apple ALC , I found a guide on how to do so here 

https://github.com/acidanthera/AppleALC/wiki/Adding-codec-support

For sleep:-

someone said that disabling the dgpu using ssdt method worked for him but we aldredy are using MacOS on igpu so it won't work I suppose

**Comment by PhantomZNeuroX** [comment]
> > Ok. but i was actually asking about the heliport issue ..
> 
> Oh, sorry.
> 
> * The heli port is working fine after modifying config.plist. even works better than the airportutility, but the issue with the sleep still exists.
> * it was still waking up on its own. that's the problem.

Hey, I added itwlm.kext to the config.pilist file but heliport still dosent work :/ any help please

**Comment by d-kanti** [comment]
@PhantomZNeuroX  did you add heliport in the login apps list ?

**Comment by PhantomZNeuroX** [comment]
@d-kanti Yup tried that aldredy, didnt work. could you provide me with your EFI folder that you are using currently (without serial number)?

I think the problem with how i entered the kext in the pilist file, i used the oc command in proper tree.

**Comment by itsdrnoob** [comment]
> @d-kanti Yup tried that aldredy, didnt work. could you provide me with your EFI folder that you are using currently (without serial number)?
> 
> I think the problem with how i entered the kext in the pilist file, i used the oc command in proper tree.

Try adding the kext via opencore configurator. Also what's the exact error, can heliport scan for wifi networks but can't connect, do you get a popup on start up saying "itlwm is not running"?

**Comment by itsdrnoob** [comment]
+
Working on a new efi, sleep working fine for me and another user with a dgpu.

**Comment by d-kanti** [comment]
> Also..
> Working on a new efi, sleep working fine for me and another user with a dgpu.
> 

Would be great if sleep also works for us.... It's really annoying to shut down and turn on every time.

**Comment by PhantomZNeuroX** [comment]
> > @d-kanti Yup tried that aldredy, didnt work. could you provide me with your EFI folder that you are using currently (without serial number)?
> > I think the problem with how i entered the kext in the pilist file, i used the oc command in proper tree.
> 
> Try adding the kext via opencore configurator. Also what's the exact error, can heliport scan for wifi networks but can't connect, do you get a popup on start up saying "itlwm is not running"?

The issue was that I was using a older version of itlwm so I downloaded it again and added it worked

Also, Thank you so much @itsdrnoob for working on a new EFI with the fix for sleep, can't wait for it :)

**Comment by itsdrnoob** [comment]
Updated.

**Comment by PhantomZNeuroX** [comment]
@itsdrnoob Jus saw that it was updated, will check it out tomorrow, what are the fixes?
sleep?
imsesages?
mic?

**Comment by itsdrnoob** [comment]
> @itsdrnoob Jus saw that it was updated, will check it out tomorrow, what are the fixes?
> sleep?
> imsesages?
> mic?

Sleep is fixed (probably for all) , oc updated, internal mic won't work, cleaned up many unnecessary things, iServices is not an efi issue cuz it works for another user on downgrading to Catalina and then updating to big sur (also works on Catalina), correct your platform info and try, even saw a reddit post so I'll link it here :

https://www.reddit.com/r/hackintosh/comments/nj8yeu/imessage_problem_instantly_logged_out/

**Comment by PhantomZNeuroX** [comment]
@itsdrnoob Oh okay, thank you so much, I am so grateful for the work you have done :)

Now we can finally close this issue XD

**Comment by d-kanti** [comment]
@PhantomZNeuroX  did you try the new efi ?

 does sleep works for you ?

**Comment by PhantomZNeuroX** [comment]
@d-kanti  I just replaced the EFI folder and booted to it, but it seems that sleep still isn't working for me just yet

**Comment by d-kanti** [comment]
@PhantomZNeuroX  well, that's depressing... 

Anyway, please let me know if you are able to make it work.

**Comment by PhantomZNeuroX** [comment]
the only change I see for now is the new OS selector screen

**Comment by PhantomZNeuroX** [comment]
> @PhantomZNeuroX  well, that's depressing... 
> 
> Anyway, please let me know if you are able to make it work.  
> 
> Seems the problems still exists. 
> 
> Are you planning to do a re-installation ?

I am planning to install Catalina and them upgrade to MacOS big sur

**Comment by PhantomZNeuroX** [comment]
@d-kanti  You mentioned before that you installed macros without having to disturb the windows partition, how did you manage to do so? could you please guide me on that?

**Comment by itsdrnoob** [comment]
@PhantomZNeuroX what are your sleep settings,  run `pmset - g` in terminal and check the output, also check dortania's guide for reference.

**Comment by itsdrnoob** [comment]
> Also, audio dosent seem to be working in the new EFI

Audio doesn't work? Does audio device show up in settings?

**Comment by PhantomZNeuroX** [comment]
oh okay, It says here thet sleep is prevented by core audiod
BTW I am on the older EFI when I ran this command

https://imgur.com/kmvprpk

**Comment by PhantomZNeuroX** [comment]
> > Also, audio dosent seem to be working in the new EFI
> 
> Audio doesn't work? Does audio device show up in settings?

Combo jack is workin , so headphones and headset mic is working, but the speaker isn't working

**Comment by itsdrnoob** [comment]
set sleep to 0 by running `sudo pmset sleep 0`. and check

**Comment by PhantomZNeuroX** [comment]
still nothing :/

**Comment by itsdrnoob** [comment]
Do a `pmset -g log | grep -e "Sleep.*due to" -e "Wake.*due to"` in terminal, is there anything causing issues

**Comment by PhantomZNeuroX** [comment]
output of pmset -g log | grep -e "Sleep.*due to" -e "Wake.*due to" 

2021-06-01 18:28:56 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=active Using Batt (Charge:63%)           
2021-06-01 18:29:05 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:63%) 196 secs  
2021-06-01 18:32:21 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=active Using Batt (Charge:62%) 8 secs    
2021-06-01 18:32:29 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:62%) 1327 secs 
2021-06-01 18:54:36 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=active Using Batt (Charge:56%) 8 secs    
2021-06-01 18:54:44 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:56%) 210 secs  
2021-06-01 18:58:14 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=active Using Batt (Charge:56%) 9 secs    
2021-06-01 18:58:23 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:56%) 197 secs  
2021-06-01 19:01:40 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=active Using Batt (Charge:55%) 9 secs    
2021-06-01 19:01:49 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:55%) 196 secs  
2021-06-01 19:05:05 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=active Using Batt (Charge:54%) 9 secs    
2021-06-01 19:05:14 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:54%) 194 secs  
2021-06-01 19:08:28 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=active Using Batt (Charge:53%) 9 secs    
2021-06-01 19:08:37 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:53%)           
2021-06-01 21:17:00 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=active Using Batt (Charge:29%) 9 secs    
2021-06-01 21:17:09 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:29%) 475 secs  
2021-06-01 21:25:04 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=active Using Batt (Charge:27%) 9 secs    
2021-06-01 21:25:13 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:27%)           
2021-06-03 17:04:46 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=active Using Batt (Charge:79%) 10 secs   
2021-06-03 17:04:56 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:79%)           
2021-06-03 17:22:28 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=active Using Batt (Charge:74%) 10 secs   
2021-06-03 17:22:38 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:74%)           
2021-06-03 18:14:19 +0530 Sleep               	Entering Sleep state due to 'Clamshell Sleep':TCPKeepAlive=active Using Batt (Charge:52%) 11 secs   
2021-06-03 18:14:30 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/User Using BATT (Charge:52%)           
2021-06-03 18:18:47 +0530 Sleep               	Entering Sleep state due to 'Clamshell Sleep':TCPKeepAlive=disabled Using Batt (Charge:51%) 9 secs    
2021-06-03 18:18:56 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/User Using BATT (Charge:51%)           
2021-06-03 20:14:54 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:63%) 9 secs    
2021-06-03 20:15:03 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:63%)           
2021-06-04 14:11:36 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:88%) 23 secs   
2021-06-04 14:11:59 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:88%)           
2021-06-04 15:05:19 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:64%) 8 secs    
2021-06-04 15:05:27 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:64%)           
2021-06-04 15:12:26 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:62%) 8 secs    
2021-06-04 15:12:34 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:62%) 198 secs  
2021-06-04 15:15:52 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:60%) 9 secs    
2021-06-04 15:16:01 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:60%)           
2021-06-04 15:21:45 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:59%) 9 secs    
2021-06-04 15:21:54 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:59%) 132 secs  
2021-06-04 15:24:06 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:58%) 9 secs    
2021-06-04 15:24:15 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:58%)           
2021-06-04 17:00:29 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:100%) 8 secs    
2021-06-04 17:00:37 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:100%) 132 secs  
2021-06-04 17:02:49 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:100%) 8 secs    
2021-06-04 17:02:57 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:100%) 132 secs  
2021-06-04 17:05:09 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:100%) 12 secs   
2021-06-04 17:05:21 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:100%)           
2021-06-04 17:13:58 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:100%) 9 secs    
2021-06-04 17:14:07 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:100%)           
2021-06-04 17:17:12 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:99%) 9 secs    
2021-06-04 17:17:21 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:99%) 222 secs  
2021-06-04 17:21:03 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:98%) 9 secs    
2021-06-04 17:21:12 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:98%) 132 secs  
2021-06-04 17:23:24 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:97%) 9 secs    
2021-06-04 17:23:33 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:97%)           
2021-06-06 17:15:51 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:100%) 14 secs   
2021-06-06 17:16:05 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:100%) 132 secs  
2021-06-06 17:18:17 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:100%) 7 secs    
2021-06-06 17:18:24 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/UserActivity Assertion Using BATT (Charge:100%) 808 secs  
2021-06-06 17:31:52 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:100%)           
2021-06-06 18:07:20 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:90%) 9 secs    
2021-06-06 18:07:29 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:90%) 177 secs  
2021-06-06 18:10:26 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:89%) 10 secs   
2021-06-06 18:10:36 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:89%)           
2021-06-06 19:01:16 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:71%) 10 secs   
2021-06-06 19:01:26 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:71%) 258 secs  
2021-06-06 19:05:44 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:70%) 9 secs    
2021-06-06 19:05:53 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:70%) 178 secs  
2021-06-06 19:08:51 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:69%) 9 secs    
2021-06-06 19:09:00 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:69%) 177 secs  
2021-06-06 19:11:57 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:68%) 9 secs    
2021-06-06 19:12:06 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:68%) 177 secs  
2021-06-06 19:15:03 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:67%) 9 secs    
2021-06-06 19:15:12 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:67%) 177 secs  
2021-06-06 19:18:09 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:66%) 9 secs    
2021-06-06 19:18:18 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:66%) 177 secs  
2021-06-06 19:21:15 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:65%) 9 secs    
2021-06-06 19:21:24 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:65%)           
2021-06-07 18:26:37 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:100%) 10 secs   
2021-06-07 18:26:47 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:100%) 131 secs  
2021-06-07 18:28:58 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:100%) 9 secs    
2021-06-07 18:29:07 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:100%) 132 secs  
2021-06-07 18:31:19 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:100%) 9 secs    
2021-06-07 18:31:28 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:100%)           
2021-06-08 03:29:36 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:100%) 8 secs    
2021-06-08 03:29:44 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:100%)           
2021-06-07 22:17:13 +0530 Sleep               	Entering Sleep state due to 'Idle Sleep':TCPKeepAlive=disabled Using Batt (Charge:96%)           
2021-06-08 09:54:05 +0530 Sleep               	Entering Sleep state due to 'Software Sleep pid=149':TCPKeepAlive=disabled Using Batt (Charge:100%) 16 secs   
2021-06-08 09:54:21 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:100%) 38 secs   
2021-06-08 09:54:59 +0530 Sleep               	Entering Sleep state due to 'Clamshell Sleep':TCPKeepAlive=disabled Using Batt (Charge:100%) 10 secs   
2021-06-08 09:55:09 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/User Using BATT (Charge:100%)           
2021-06-08 10:57:23 +0530 Sleep               	Entering Sleep state due to 'Clamshell Sleep':TCPKeepAlive=disabled Using Batt (Charge:76%) 9 secs    
2021-06-08 10:57:32 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/User Using BATT (Charge:76%) 29 secs   
2021-06-08 10:58:01 +0530 Sleep               	Entering DarkWake state due to 'Software Sleep pid=149':TCPKeepAlive=disabled Using Batt (Charge:76%)           
2021-06-08 10:58:16 +0530 Sleep               	Entering Sleep state due to 'Software Sleep pid=149':TCPKeepAlive=disabled Using Batt (Charge:76%) 20 secs   
2021-06-08 10:58:36 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:76%) 40 secs   
2021-06-08 10:59:16 +0530 Sleep               	Entering Sleep state due to 'Software Sleep pid=149':TCPKeepAlive=disabled Using Batt (Charge:75%) 9 secs    
2021-06-08 10:59:25 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:75%) 59 secs   
2021-06-08 11:00:24 +0530 Sleep               	Entering Sleep state due to 'Software Sleep pid=149':TCPKeepAlive=disabled Using Batt (Charge:75%) 9 secs    
2021-06-08 11:00:33 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:75%) 40 secs   
2021-06-08 11:01:13 +0530 Sleep               	Entering Sleep state due to 'Clamshell Sleep':TCPKeepAlive=disabled Using Batt (Charge:75%) 24 secs   
2021-06-08 11:01:37 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/User Using BATT (Charge:74%)           
2021-06-08 11:24:57 +0530 Sleep               	Entering Sleep state due to 'Software Sleep pid=150':TCPKeepAlive=disabled Using Batt (Charge:66%) 9 secs    
2021-06-08 11:25:06 +0530 Wake                	Wake from Normal Sleep [CDNVA] : due to power-button/Lid Open Using BATT (Charge:66%)

**Comment by itsdrnoob** [comment]
seems clear. Check battery settings in sys prefs, restore the default settings and check

**Comment by PhantomZNeuroX** [comment]
already tried that didnt work

**Comment by PhantomZNeuroX** [comment]
sudo peseta -g assertions 
output:-
2021-06-08 11:54:14 +0530 
Assertion status system-wide:
   BackgroundTask                 0
   ApplePushServiceTask           0
   UserIsActive                   1
   PreventUserIdleDisplaySleep    0
   PreventSystemSleep             0
   ExternalMedia                  0
   PreventUserIdleSystemSleep     1
   NetworkClientActive            0
Listed by owning process:
   pid 188(coreaudiod): [0x000001cd00018327] 00:00:07 PreventUserIdleSystemSleep named: "com.apple.audio.AppleHDAEngineOutput:1F,3,0,1,1:0.context.preventuseridlesleep"  
	Created for PID: 821. 
   pid 146(WindowServer): [0x00000035000980ba] 00:00:00 UserIsActive named: "com.apple.iohideventsystem.queue.tickle serviceID:100000455 name:IOHIDEventDriver product:Keyboard eventType:3"  
	Timeout will fire in 120 secs Action=TimeoutActionRelease
Kernel Assertions: 0x4=USB
   id=501  level=255 0x4=USB creat=08/06/21, 11:56 AM description=com.apple.usb.externaldevice.14a00000 owner=IOUSBHostDevice
Idle sleep preventers: IODisplayWrangler

**Comment by itsdrnoob** [comment]
kill coreaudiod

**Comment by PhantomZNeuroX** [comment]
killed it via activity monitor but It stated again :/

**Comment by itsdrnoob** [comment]
check in activity monitor under energy tab if any process is listed as "yes" under preventing sleep

**Comment by PhantomZNeuroX** [comment]
@itsdrnoob none are listed as yes, but a few do have a "-" instead of yes or no

**Comment by PhantomZNeuroX** [comment]
The other user who you mentioned has had success with sleep, which model does he own?
Horizon mx350 or the normal one with mx 250?

**Comment by d-kanti** [comment]
@PhantomZNeuroX  i think sleep works on i3-igpu & i5-mx250.... It's the mx350 one which are have the issue.... That's why we are experiencing such a situation..

**Comment by PhantomZNeuroX** [comment]
> @PhantomZNeuroX  i think sleep works on i3-igpu & i5-mx250.... It's the mx350 one which are have the issue.... That's why we are experiencing such a situation..

Yup tht looks to be the case, @d-kanti  can you try the new EFI once just to check if the sleep it is aproblem only I am experiencing?

**Comment by PhantomZNeuroX** [comment]
> @d-kanti  You mentioned before that you installed macros without having to disturb the windows partition, how did you manage to do so? could you please guide me on that?

@d-kanti

**Comment by d-kanti** [comment]
> > @PhantomZNeuroX  i think sleep works on i3-igpu & i5-mx250.... It's the mx350 one which are have the issue.... That's why we are experiencing such a situation..
> 
> Yup tht looks to be the case, @d-kanti  can you try the new EFI once just to check if the sleep it is aproblem only I am experiencing?

The whole process is a lengthy process. Installing mac, configuring, installing softwares, packages....  It all does take a lot of time and energy.  And currently i am running short on time. That is keeping me from trying installing mac as i just configured my whole development environment on **fedora** .  I stopped using macos just because of the sleeping issue.  That's why i was asking for what results you got.  If the issue still exists, it will be a lot of work, and getting nothing as result.  

    I was thinking about trying once, but this isn't a good time for experiments for me. I will try it some days later though..

**Comment by d-kanti** [comment]
@PhantomZNeuroX 

All guide to install mac using open cv suggests to format the whole drive using mac's disk utils.  **The first step is to not to do that.** 

I had installed windows first. Windows itself created a guid partitioning system. 250mb EFI partition which contained the windows boot loader (and did not touched that ever) .  Rest for the WinOS. 
 So, i already had windows with working windows boot manager.  The from windows, i created 2 partitions. 

1) one partition(about 160gb) and named it "mac" just to be able to understand clearly which partition i am targetting.
2) And another 200mb partition, and formatted it into FAT32 using **windows disk mamager** . 

Only then i booted into the mac installer. Using mac's disk utils, i only formatted the  'mac' partition (160gb created previously) into APFS (mac journal extended didn't work for me) and installed mac on that drive.....  After installation completed, i mounted the '2nd 200mb Partition'  which i created previously and just pasted the EFI folder in that. 

It worked fine. Only difficulty was that I had to set any one efi as default and had to use boot menu to select the other efi partition to boot.  As per my need, i left windows default and whenever i had to boot mac, i used F12.  It worked fine. 

(Note - you still can't boot into windows boot manager from Open Core.... It just doesn't work.) 


_I hope that explanation itself is enough for you to understand, however i can attach screenshots or screen recording if you want._

**Comment by PhantomZNeuroX** [comment]
> @PhantomZNeuroX
> 
> All guide to install mac using open cv suggests to format the whole drive using mac's disk utils. **The first step is to not to do that.**
> 
> I had installed windows first. Windows itself created a guid partitioning system. 250mb EFI partition which contained the windows boot loader (and did not touched that ever) . Rest for the WinOS.
> So, i already had windows with working windows boot manager. The from windows, i created 2 partitions.
> 
> 1. one partition(about 160gb) and named it "mac" just to be able to understand clearly which partition i am targetting.
> 2. And another 200mb partition, and formatted it into FAT32 using **windows disk manager** .
> 
> Only then i booted into the mac installer. Using mac's disk utils, i only formatted the 'mac' partition (160gb created previously) into APFS (mac journal extended didn't work for me) and installed mac on that drive..... After installation completed, i mounted the '2nd 200mb Partition' which i created previously and just pasted the EFI folder in that.
> 
> It worked fine. Only difficulty was that I had to set any one efi as default and had to use boot menu to select the other efi partition to boot. As per my need, i left windows default and whenever i had to boot mac, i used F12. It worked fine.
> 
> (Note - you still can't boot into windows boot manager from Open Core.... It just doesn't work.)
> 
> _I hope that explanation itself is enough for you to understand, however i can attach screenshots or screen recording if you want._

Thank you, yup I agree booting windows from OpenCore docent work fore me via the method I use either

**Comment by d-kanti** [comment]
> > @PhantomZNeuroX
> > 
> > All guide to install mac using open cv suggests to format the whole drive using mac's disk utils. **The first step is to not to do that.**
> > 
> > I had installed windows first. Windows itself created a guid partitioning system. 250mb EFI partition which contained the windows boot loader (and did not touched that ever) . Rest for the WinOS.
> > So, i already had windows with working windows boot manager. The from windows, i created 2 partitions.
> > 
> > 1. one partition(about 160gb) and named it "mac" just to be able to understand clearly which partition i am targetting.
> > 2. And another 200mb partition, and formatted it into FAT32 using **windows disk manager** .
> > 
> > Only then i booted into the mac installer. Using mac's disk utils, i only formatted the 'mac' partition (160gb created previously) into APFS (mac journal extended didn't work for me) and installed mac on that drive..... After installation completed, i mounted the '2nd 200mb Partition' which i created previously and just pasted the EFI folder in that.
> > 
> > It worked fine. Only difficulty was that I had to set any one efi as default and had to use boot menu to select the other efi partition to boot. As per my need, i left windows default and whenever i had to boot mac, i used F12. It worked fine.
> > 
> > (Note - you still can't boot into windows boot manager from Open Core.... It just doesn't work.)
> > 
> > _I hope that explanation itself is enough for you to understand, however i can attach screenshots or screen recording if you want._
> 
> Thank you, yup I agree booting windows from OpenCore docent work fore me via the method I use either

Did my answer satisfied your query ? And did it satisfy you need ?

**Comment by PhantomZNeuroX** [comment]
> > > @PhantomZNeuroX
> > > 
> > > All guide to install mac using open cv suggests to format the whole drive using mac's disk utils. **The first step is to not to do that.**
> > > 
> > > I had installed windows first. Windows itself created a guid partitioning system. 250mb EFI partition which contained the windows boot loader (and did not touched that ever) . Rest for the WinOS.
> > > So, i already had windows with working windows boot manager. The from windows, i created 2 partitions.
> > > 
> > > 1. one partition(about 160gb) and named it "mac" just to be able to understand clearly which partition i am targetting.
> > > 2. And another 200mb partition, and formatted it into FAT32 using **windows disk manager** .
> > > 
> > > Only then i booted into the mac installer. Using mac's disk utils, i only formatted the 'mac' partition (160gb created previously) into APFS (mac journal extended didn't work for me) and installed mac on that drive..... After installation completed, i mounted the '2nd 200mb Partition' which i created previously and just pasted the EFI folder in that.
> > > 
> > > It worked fine. Only difficulty was that I had to set any one efi as default and had to use boot menu to select the other efi partition to boot. As per my need, i left windows default and whenever i had to boot mac, i used F12. It worked fine.
> > > 
> > > (Note - you still can't boot into windows boot manager from Open Core.... It just doesn't work.)
> > > 
> > > _I hope that explanation itself is enough for you to understand, however i can attach screenshots or screen recording if you want._
> > 
> > Thank you, yup I agree booting windows from OpenCore docent work fore me via the method I use either
> 
> Did my answer satisfied your query ? And did it satisfy you need ? 

Yup, thank you so much. I am going to be installing Catalina so that IServices work and see if sleep works as well

I used to have to reinstall windows after every atempt to install MacOS which used to take alot of extra time

Thanks

**Comment by PhantomZNeuroX** [comment]
Hey @itsdrnoob, I found 16 AppleALC layouts for ALC256, have you tested them all?, if not shall I go ahead and test them?

**Comment by chadify** [comment]
@itsdrnoob did you patch your Laptop's DSDT to make sleep work?

**Comment by PhantomZNeuroX** [comment]
@itsdrnoob  I installed macOS Catalina and now am able to use Imessages will update to big sur now. Sleep not working

**Comment by itsdrnoob** [comment]
@PhantomZNeuroX if you have windows installed, check what's the BIOS device name value of your dgpu in device manager.
@chadify Yup the DSDT's are patched acc to my system.

**Comment by PhantomZNeuroX** [comment]
Bios device name value : - \_SB.PCI0.RP05.PXSX

**Comment by itsdrnoob** [comment]
Yup. You've to patch the dsdt accordingly

**Comment by itsdrnoob** [comment]
@PhantomZNeuroX 
[Archive.zip](https://github.com/itsdrnoob/Mi-NoteBook-14-Hackintosh/files/6620720/Archive.zip)
try replacing these in you efi folder/ACPI

**Comment by PhantomZNeuroX** [comment]
> @PhantomZNeuroX 
> [Archive.zip](https://github.com/itsdrnoob/Mi-NoteBook-14-Hackintosh/files/6620720/Archive.zip)
> try replacing these in you efi folder/ACPI
> 

sure, also I have been having this issue where I am not able to update to big sur. I have downloaded the installer but when it finishes and says that the mac will restart, instead of restart it just logs me out and after login the download starts again

any idea why?

**Comment by PhantomZNeuroX** [comment]
> @PhantomZNeuroX 
> [Archive.zip](https://github.com/itsdrnoob/Mi-NoteBook-14-Hackintosh/files/6620720/Archive.zip)
> try replacing these in you efi folder/ACPI
> 

still not working ;/

**Comment by itsdrnoob** [comment]
[Archive.zip](https://github.com/itsdrnoob/Mi-NoteBook-14-Hackintosh/files/6620947/Archive.zip)

replace SSDT-dGPU-Off, add SSDT-MEM2, remove SSDT-NoHybGfx, make changes in config.plist also, and check

**Comment by itsdrnoob** [comment]
@PhantomZNeuroX 

[Archive.zip](https://github.com/itsdrnoob/Mi-NoteBook-14-Hackintosh/files/6620953/Archive.zip)

replace SSDT-dGPU-Off, add SSDT-MEM2, remove SSDT-NoHybGfx, make changes in config.plist also, and check

**Comment by PhantomZNeuroX** [comment]
> @PhantomZNeuroX 
> 
> [Archive.zip](https://github.com/itsdrnoob/Mi-NoteBook-14-Hackintosh/files/6620953/Archive.zip)
> 
> replace SSDT-dGPU-Off, add SSDT-MEM2, remove SSDT-NoHybGfx, make changes in config.plist also, and check

tried this but it won't boot now

**Comment by itsdrnoob** [comment]
> tried this but it won't boot now

What's the output in boot screen, have you disabled SSDT-NoHybGfx from config

**Comment by PhantomZNeuroX** [comment]
> > tried this but it won't boot now
> 
> What's the output in boot screen, have you disabled SSDT-NoHybGfx from config

I deleted it and then a took a pc clean snapshot using proper tree, couldn't see the output properly, will try again and record

**Comment by d-kanti** [comment]
@itsdrnoob  This issue is getting longer everyday, has 147 comments already, 148 including this one. Who knows how long it will get... 

I was thinking, how about creating a discussion forum instead of discussing in the issue section ?  
github's new discussion feature is well, good enough!!

**Comment by PhantomZNeuroX** [comment]
Ya that's a awesome idea, @itsdrnoob  can you enable it?

**Comment by itsdrnoob** [comment]
Discussions enabled.
